language: node_js
node_js:
    - "0.10"
    - "4.0"
    - "5.0"
    - "6.0"

notifications:
    email: false

before_install: npm install -g codeclimate-test-reporter
install: npm install
script: babel-node ./node_modules/.bin/isparta cover ./node_modules/.bin/_mocha
after_success: codeclimate < coverage/lcov.info
